### ISSUE TITLE
Decide on the green colore tone used in Bisq 2

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1255]
The green color used in Bisq 1 is quite intense on Linux (I assume Windows use the same color profile). On OSX it looks ok.

In Bisq 1 those are the base colors:
-bs-color-primary: #25b135; (left menu, progr. indicator,...)
-bs-color-primary-dark: #2ea33c; (right menu, action button,...)

In Bisq 2 the base color was changed to #56ae48. The color is a good compromise which looks ok both on Linux and Mac.
For large buttons we need to adjust to a darker/less intense variation. A `derive(#56ae48, -15%)` worked for me on both OSX and Linux.

See also: 
https://github.com/bisq-network/bisq-website/issues/478

**Comment by HenrikJannsen** [comment]
@axpoems 
From your last PR it seems that we stick with the Bisq1 green color for the logo (which makes sense).
The green tone in the app can then be different depending on the usage.
For small areas where its good to have a strong signal effect I would suggest to stick with the bisq1 green.
For default state of standard buttons i would suggest the bisq2 green from Pedro. 
If the button green is still too intense for large buttons we can adjust that further (IMO it is fine - one has to compare with all OS, they look quite different and those color suggestions look like a good compromise to me).

Suggestion:
```
-bisq-green: #25b135;
-fx-default-button: derive(#56ae48, -15%);
-bisq-green-hover: derive(-fx-default-button, 10%);
-bisq-green-pressed: derive(-fx-default-button, -5%);
```

If those suggestions dont work well for you can you offer your suggestions?

Bisq 1 green: #25b135 
Bisq 2 green: #56ae48

**Comment by axpoems** [comment]
@HenrikJannsen - As you mentioned, I believe it's a good idea to keep the logo colour consistent at `#25b135`, while using another shade of green with some variations for the rest of the application. The green already implemented, `#56ae48`, seems like a good choice.

So far, I've tested it on Windows, and it appears to work well. I'm planning to test it on Linux as well to ensure uniformity.

Regarding the variations, I'd like to propose a slightly different approach. Instead of using dynamic derived variations, which can sometimes be less intuitive, I suggest choosing two or three specific shades of green from the palette. These selections could be related to your initial proposal, like this:

```
-fx-default-button: #3c942e;  /* (-10% from #56ae48) / derive(#56ae48, -15%) */
-bisq-green-hover: #49a13b;  /* (-5% from #56ae48) / derive(-fx-default-button, 10%) */
-bisq-green-pressed: #2f8721;  /* (-15% from #56ae48) / derive(-fx-default-button, -5%) */
```

&#12288;
<img width="1143" alt="56ae48_pallet" src="https://github.com/bisq-network/bisq2/assets/145597137/a3999f16-e007-4078-b195-a60e30894cc7">
&#12288;

This way, we can work with some predefined colours from the palette, making it more straightforward and visually consistent. What are your thoughts on this approach, and if you have specific shades in mind from the palette you'd like to use.

**Comment by HenrikJannsen** [comment]
Looks good. I tested those colors on OSX and Linux and looks ok to me on both platforms.

**Comment by axpoems** [comment]
I've been testing the greens and made an adjustment to the previously proposed palette, aiming for a slightly softer, less vibrant look that aligns better with the hue of the bisq 2 green #56ae48.

<img width="656" alt="56ae48_palle2t" src="https://github.com/bisq-network/bisq2/assets/145597137/72547a64-c9ff-4f4a-998b-7fe231b69520">

**Comment by HenrikJannsen** [comment]
Can we close the issue @axpoems ?

**Comment by axpoems** [comment]
Yes, I think with this we have defined all the green shades needed for the Bisq 2 application.
I didn't add all of them into the codebase (only a small selection - see #1324), but we can use this as the reference in case we need more shades, like lighter shades.
