### ISSUE TITLE
Update the reputation calculation for 'Burning BSQ'

### ISSUE THREAD

**Issue by darawhelan** [bisq-network/bisq2#1454]
I think both 'Burning BSQ' reputation score not decay but instead increase over time:

## Current reputation calculations

**Burning BSQ**

![Burning BSQ](https://github.com/bisq-network/bisq2/assets/121062323/38124d29-2723-42ef-9b18-5a3c9c915cb8)

Currently reputation burns to zero after 100 days

## Proposed reputation calculations

I propose reputation for burning BSQ should increase by a factor of 2 over 3,650 days.

At the end of 3,650 days the full reputation score should persist.

Reasoning:

This way burned reputation is more persistent. Users can burn more reputation to increase their reputation score to compete with other sellers.

There should be an assumption that a Seller on Bisq Easy is more trusted the longer they are on the platform. Changing the way reputation is calculated for BSQ burners helps give Sellers with longevity more of an advantage over new sellers. This makes sense as they will be more trusted.

A user who has burnt 300 BSQ will effectively be treated as having burnt 600 BSQ (if nothing else changes) after 3,650 days.

The changes above will also promote Burning BSQ over Bonding BSQ. It does not make sense currently the way the reputation scores are calculate that Bonding BSQ for 2 years gives a better reputation, over time, than burning BSQ.

Linked issue:

https://github.com/bisq-network/bisq2/issues/1402

**Comment by HenrikJannsen** [comment]
Hm...
Reason for the current model is to motivate for repeated burning as it can be considered as "work" to be active and burn every month. It also helps the DAO to earn some revenue from Bisq Easy as it creates more incentive to burn again.
Otherwise if a seller has gained a high reputation they have no incentive to burn again.

Good point with BSQ bond, we need to finetune the models to avoid that. Burning BSQ should be the highest value, and is the only way how Bisq can earn indirectly a kind of trade fee.

**Comment by darawhelan** [comment]
This issue has been replaced with https://github.com/bisq-network/bisq2/issues/1495 and can be closed
