### ISSUE TITLE
Are private chats possible with other users?

### ISSUE THREAD

**Issue by darawhelan** [bisq-network/bisq2#1461]
Are private chats possible with other users?

There is a private chat section but I am not sure how to start one. Is this for moderators and mediators to contact users? Or for users to contact other users?

Chatting to Seller's in the Matrix 'get your first bitcoin' room I am aware that most trades end up being agreed DM. User messages a seller they like they like to look of (positive comments about past trades from other users etc) and agrees a trade with them (currency, amount, markup, payment method). Might be nice if Bisq Easy enabled this.

Screenshots demonstrating how I cannot find the option to DM Joe (should be on his profile)

![chat](https://github.com/bisq-network/bisq2/assets/121062323/49b63af5-4b61-421f-9308-8cadf51d534e)

![chat 2](https://github.com/bisq-network/bisq2/assets/121062323/c6b75ae9-2230-446e-bc4f-a2a2fb1e6a1e)

![chat 3](https://github.com/bisq-network/bisq2/assets/121062323/2cbfb01c-515d-4459-a1b4-35d9b66a2d8c)

**Comment by darawhelan** [comment]
Also Why has Joe got a 1 star reputation on one screen and a 2 star reputation on another?

**Comment by HenrikJannsen** [comment]
I think you created the Joe user on the same app. Then we do not show PM buttons as it does not make sense to PM yourself.

Here its like it looks when you have the peer on a diff. app:
![Screenshot from 2023-12-03 12-34-10](https://github.com/bisq-network/bisq2/assets/116298498/f251e76d-bfd7-48b8-8a51-93331f79ff26)


![Screenshot from 2023-12-03 12-36-07](https://github.com/bisq-network/bisq2/assets/116298498/7e45b254-68ca-4c47-8571-b170fca8c031)

> Also Why has Joe got a 1 star reputation on one screen and a 2 star reputation on another?

The star display is using random data atm as otherwise all would have 0 stars. But good reminder to remove that before launch.
