### ISSUE TITLE
Improve user profile screen

### ISSUE THREAD

**Issue by chimp1984** [bisq-network/bisq2#151]
The user profile screen is very basic atm.
- We should allow to delete an identity if not used in a channel. If it was used we should show a warning. We could keep deleted identities in a "trash folder" where the user can re-activate it once they found out they deleted it by mistake.
- We should also add a context/description/tag field where the user can assign an identity to some use case, e.g. identity which is used for EUR-trades can be market with a "EUR" tag and that tag is shown next to the icon/username. 
- We should add a public profile description where the user can share some statement or info about themself (like on twitter)
- We should add at least for trusted sellers a "term of trade" field where they can define their TACs for trading
- Once we have fiat accounts implemented we should allow the user to attach fiat accounts so that could be later used in privat messages to quickly post the required account (banking) info to the peer. Maybe could be done via a simple text field like the TAC as well, but would be only used in PM (as opposed to TACs which might be used in public chats). The user could attach those predefined text then from some options in the chat overlay menu (maybe under "other options").

**Comment by UX-P** [comment]
Simple/basic is good.  Here is an example of the[ user profile ](https://www.figma.com/proto/xBMDm3Fvf5OEYqczQw87DS/User-Profile?node-id=467%3A565&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=467%3A565)design

In this example the new trader is on the left and the rep traders profile is on the right (clickable prototype)

### **Reputable Trader Profile**

The new trader clicks on available offer and the reputable trader profile on the right appears

There is a thick coloured ring representing the traders level, otherwise a badge can be used. The ring is perhaps more simplistic  

The Trading level is displayed

Burn score- Using the term ‘score’ so that the figures do not have a financial association.

Account age if necessary 

Meatball menu: mention, ignore and report

### **New Trader Profile** 

User profile on the left, click on user image for dropdown options

The new trader can click on their profile image and a dropdown option menu appears with the option to manage account, switch profiles and delete. I’m not sure if the option to delete this profile should be displayed here so maybe another essential option can replace this.

**Comment by chimp1984** [comment]
Great thanks! Helps a lot to get those wireframes!
