### ISSUE TITLE
Find better solution for create offer button and user profile selection at input field

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1572]
When a user has multiple profiles we show the profile selection next to the create offer button at the input box (only at public chats).
We should find a better solution for that situation.

@axpoems Any idea?

**Comment by axpoems** [comment]
Yes, I'm already working on this. I'll be relocating the 'Create Offer' button to another place. I'll be uploading the mock-up for the 'OfferBook' tab very soon.

**Comment by axpoems** [comment]
<br>

This is the mock-up of the review and solution proposed for the Offerbook.

<br>

![offerbook2](https://github.com/bisq-network/bisq2/assets/145597137/46405291-0d5b-4613-8169-ca818b650ad7)

<br>

With the drop-down menus options.

![offerbook2_dp-menu](https://github.com/bisq-network/bisq2/assets/145597137/a468f1b2-17a3-4da7-ad82-66411e244783)

<br>

@HenrikJannsen Looking forward to hear your thoughts about it.

**Comment by HenrikJannsen** [comment]
Looks good! 

My only concern is that in minimal width size the new left market navigation takes some space.
But we could maybe only show that when width is > xxx px and otherwise use the dropdown similar as it is now.
I also expect that there will not be too many markets filled with offers, at least in the bootstrap phase. Then the navigation looks a bit bad as its visible that only maybe 4-6 markets have offers at all. Hope I am wrong on that ;-).

But like the layout and the filter options.
The Higher/Lower offers is probably the number or offers. Not sure if the sorting by low offers is much useful. Maybe we could use "Most offers" and "Most messages" instead?

Not sure if it would be better to show also the fiat next to the BTC icon at the selected market. Designwise it looks nice as it is, so not sure if both icons would fit that well.

The new send icon looks a bit too sharp to me. Maybe a paper-plane like send button would be better?

**Comment by axpoems** [comment]
> I assume the star is a favorite feature. How to add an item as favorite?

I have some ideas on how to do that. I am thinking about implementing this as an independent feature. I will create a separte issue for this.



> My only concern is that in minimal width size the new left market navigation takes some space.
> But we could maybe only show that when width is > xxx px and otherwise use the dropdown similar as it is now.

I don't see the necessity for this. This is the same as the private chats layout and I have  tested it and it looks good on smaller screens.



> I also expect that there will not be too many markets filled with offers, at least in the bootstrap phase. Then the navigation looks a bit bad as its visible that only maybe 4-6 markets have offers at all. Hope I am wrong on that ;-).

Well at the bootstrap phase everyone should understand is empty. It could also serve as an invitation to someone make some offers in that market. 



> But like the layout and the filter options.
> The Higher/Lower offers is probably the number or offers. Not sure if the sorting by low offers is much useful. Maybe we could use "Most offers" and "Most messages" instead?

Yes, I like those suggestions as well.



> Not sure if it would be better to show also the fiat next to the BTC icon at the selected market. Designwise it looks nice as it is, so not sure if both icons would fit that well.

I have tried that out, but it looks somewhat redundant since the flag is already below. Anway  I will play a little bit more with this when implementing it and see if there's a better option.


> The new send icon looks a bit too sharp to me. Maybe a paper-plane like send button would be better?

This is just for the mock-up, although it is was taken from a screenshoot of the current icon.
We can update the icon as you mention.
