### ISSUE TITLE
Make sure we can switch to EquiHash later without requiring the peer for an update

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1613]
We need to ensure that once https://github.com/bisq-network/bisq2/issues/1612 is completed we can switch to EquiHash without requiring an update of the peer.

We do not want to use the capability feature for that as that could be used to manually stick to the less desired HashCash algorithm.

One way would be that we ship both PoW algorithms and the security manager publishes the trigger for using EquiHash.
This would be a bit tricky as the current implementation would require yet unknown changes in parameters to fix the current problems. One option would be that the security manager publishes the parameters, but it is unknown yet if that will be sufficient.

As it seems there is no easy solution we could fall back to the update mechanism with forced updates with a long lead time.
We can expect that there might be anyway a requirement for such an update if critical bugs are discovered in the network or trade protocol layers. Such an event could then be used to pack also the switch to EquiHash into that forced update.

Whatever the solution is, we should be sure that at release we are prepared for a later update to EquiHash.

**Comment by namloan** [comment]
looking into this

**Comment by djing-chan** [comment]
@namloan I had a similar use case for the inventory request algorithm.
See https://github.com/bisq-network/bisq2/issues/1611 and https://github.com/bisq-network/bisq2/pull/1626 and https://github.com/bisq-network/bisq2/pull/1626 

The idea is to use the new `Feature` for the supported features of a node. We get the peers capability at the initial handshake.
Further I added a config entry for the list of preferred implementations. We do then a match of my preferred to the peers supported ones and select the algorithm to use.
The different implementations use a common interface/base class and the outer service class deal with those. The selection of the concrete implementation is based on that match of the peer supported features any my preferred ones.

For the PoW algorithm we could use the same model and set the preferred algo to EquiHash once the impl. is ready as well as add it to the features. Once rolled out, those users who have updated can use EquiHash with peers who have updated as well, otherwise fall back to HashCash.
Once we do not want to support HashCash anymore we simple remove it from the features, thus peers who have still not updated (assume several months later) cannot connect to us anymore. This would be a soft push for update without strong enforcement. As long there are sufficient not-updated peers the user still can use the network. So its more a user-enforced softfork style.

What do you think?
If you agree, do you want to implement it yourself or should I do it for the pow domain?

**Comment by namloan** [comment]
thanks @djing-chan, makes sense. I think it'd be more efficient if you implement yourself if you have the capacity.

**Comment by DrColver** [comment]
@djing-chan I've tried to understand the PoW issue, but I might be missing something. The originator of a message performs the PoW, and network nodes forward the messages if enough PoW according to current difficulty level.

With this suggested upgrade path, wouldn't the nodes who don't upgrade gradually split from the rest of the network? Is that indented? Direct messages would still use the old algorithm so trades and private chats shouldn't be affected, but public chat rooms and similar data would be incomplete.

**Comment by djing-chan** [comment]
@DrColver Thanks for your inputs!
The data distribution works by re-broadcasting added data and the sender has to do the PoW for that forwarding message. So it is a peer-to-peer connection between the one who received the data and one of his peers to whom he sends the data.

See `NetworkEnvelope` which is the outer message containing the PoW (`AuthorizationToken`). The data which was published (e.g. Offer) does not contain PoW.

The mentioned fork risk thought is still there but it is manageable if the majority of nodes are not actively hostile.
E.g. We use HashCash only at release. Once we have EquiHash ready, we deploy a default config where both are supported (EquiHash added as feature to capability) and the myPreferredFilterTypes is set to [EquiHash, HashCash]. From here on a minority who has updated will most likely fall back to HashCash if their peer has not updated yet. Over time when the majority has updated, EquiHash will be used more. Once we know that the majority has updated we can remove HashCash from the features. From that moment on updated nodes will not connect to the minority of not-updated nodes anymore. Thus the minority either stays in their own small network or start to update as well.

Only in case there would be roughly 50/50 split of the network it might lead to a stalemate. But that should be avoidable by not removing the HashCash from the features if there is not clear a high majority updated.

There might be more options but I assume that is not needed. E.g. we could increase the difficulty for peers who use the non-preferred version. So without removing the feature we could increase the PoW for not updated nodes.

**Comment by axpoems** [comment]
@djing-chan are we able to get network statistics of the capabilities being used and thus monitor usage?

**Comment by djing-chan** [comment]
At the moment there is no network-wide monitoring, only locally for each node. A monitoring concept has to be developed with privacy protection in mind.
