### ISSUE TITLE
`Message receipt acknowledge` state not updated correctly

### ISSUE THREAD

**Issue by axpoems** [bisq-network/bisq2#1752]
From the delivery states, it doesn't seems like `Message receipt acknowledge` is updated correctly - which seems confusing.

![image](https://github.com/bisq-network/bisq2/assets/145597137/a42ab130-71b3-48d2-9bc3-99c3b26953b1)

**Comment by HenrikJannsen** [comment]
Can you specify whats wrong? 
We show only for messages sent by ourselves the state. First is CONNECTING (spinner icon), then if direct send succeeded SENT, once we got a AckMessage for it we show ACK_RECEIVED (green check icon).
If no direct connection then we send a mailbox msg. First state here is TRY_ADD_TO_MAILBOX (share icon, usually not shown as its very quick state transition to next), then ADDED_TO_MAILBOX (cloud upload icon). Once the peer goes online and send the AckMessage we show MAILBOX_MSG_RECEIVED (cloud download icon).
If anything fails we show the FAILED state. If we have a persisted message we show the green refresh icon (retry send), otherwise the red exclamation icon.

**Comment by axpoems** [comment]
I see, the confusion then relies on the fact that the end state is different depending on the connection used and thus reflected like this in the UI. So one can wonder if both messages were indeed read by the peer or not.
I think it's interesting to know the states of the messages. 

Closing this and using the following issue #1756 to look more into how to show the states.
