### ISSUE TITLE
Enhance instructions for importing account age/signed witness

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1834]
I saw many reports on the app chat that users fail to import account age/signed account age. It is clearly described how to do it, but ppl are not following it. 
Any ideas how we can make the communication for that better?

@axpoems @pedromvpg @cbeams @pazza83 Any ideas?

**Comment by pedromvpg** [comment]
<img width="1512" alt="image" src="https://github.com/bisq-network/bisq2/assets/807505/20c65ce3-0d4e-4a7d-a1b8-df75d7eff1f9">
<img width="1468" alt="image" src="https://github.com/bisq-network/bisq2/assets/807505/6467f3e4-512e-44ba-8f00-e4fc999683da">

Maybe we can add a screenshot image of the ACCOUNT screen on bisq 1?

**Comment by pedromvpg** [comment]
It'a a little confusing that the user has to add data to the clipboard but then doesn't paste it anywhere. 

Maybe we can add an extra field where the user needs to paste the data.

<img width="1442" alt="image" src="https://github.com/bisq-network/bisq2/assets/807505/63d9db91-da83-41c0-9d14-6be3b2c8a425">

**Comparison**

![image](https://github.com/bisq-network/bisq2/assets/807505/f41948fe-d12c-41a7-888a-d4920146570f)
**Option 1**
2 columns

![image](https://github.com/bisq-network/bisq2/assets/807505/e060ef00-e536-4bf8-9495-9aa96f957f44)
**Option 2**
Single column, no title
Nav link “import” instead of “how-to”

**Comment by HenrikJannsen** [comment]
Thanks @pedromvpg ! Option 2 looks better to me. We should also make it more explicit in Bisq 1 with adding the profile ID field and show the json content which will be copied.

**Comment by darawhelan** [comment]
It took me a few attempts.

I was using two devises so the copy instructions on it's own was a little confusing. I saw a user in Matrix having the same issue.

I agree the instruction presented above make it a lot clearer.
