### ISSUE TITLE
Enhance communication how reputation works in Bisq Easy

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1835]
We would need a more prominent space to explain the reputation system.
Many users do not understand the concept and do not go the resources in the app.
Maybe at Dashboard we could add something like recommendations which can be maybe even fed by remote data published by the moderator or other bonded roles?
E.g. If we see that users get hot on some topic the moderator has a dedicated and very visible space to transport messages. Could be also in the style of the notification panel (like news banners).

@axpoems @pedromvpg @cbeams @pazza83 Any ideas?

**Comment by pedromvpg** [comment]
I like the idea of a banner. 
What would it read? All the same for all users, or specific to the user/account?

**Comment by HenrikJannsen** [comment]
I think it can be generic.

**Comment by axpoems** [comment]
I propose the following:

* Add new section in dashboard dedicated to the reputation. I also think it would be a good idea if this section could be controlled by the moderator. Also I like Pedro's proposal of customising it per user, so in the example below, we could show the sections that have been completed and the ones remaining to be done.

![image](https://github.com/bisq-network/bisq2/assets/145597137/e32f3e25-a76a-4fb4-aaff-96970c456205)

* Introduce dedicated section for Reputation. The idea here is to move all the content in "User Section > Reputation tab" to this section, giving it more space and visibility, as now it's a little bit hidden inside the pop-ups. A part from that, we can add here as well the explanation of the star score system (score table tab).

![image](https://github.com/bisq-network/bisq2/assets/145597137/8f1c6278-12ca-4ac5-9cd2-bf27127dda53)

The above mock-ups are just to share my initial thoughts on how I would give more visibility and structure the reputation content. So it's not fully completed.

**Comment by cbeams** [comment]
I like the "Bisq Reputation Ribbon" graphic as shown above.

I don't think it's a good idea, though, to display it as a top level entry in the in the left nav.

To get into why and where I think it might be better placed, I'll first make a more general set of suggestions about the left nav.

I'll start by laying out the problems I see with the nav as it is now in v2.0.1.

Right now, there is a mix of elements in the left nav that make it hard to understand what we're trying to do. 

The first thing is that Bisq Easy comes above "Trading protocols", when Bisq Easy _is a_ trading protocol, and should therefore logically be a sub-item of Trading protocols.

The second thing is that we have a mix of grammatical modes in the nav item labels. The "Learn" item is a verb, and actively incites the user to engage in learning by clicking on it, while the "Discussions" and "Events" items are nouns, and passively inform the user as to what they'll find if they happen to click on them.

"Events" is non-ideal for an additional reason, too, which is that when one does click on it, they see "Conferences" and "Meetups", which are indeed events and thus make sense, but they also see "Podcasts" which are not events in the normal sense of the word, and they also see "Trade" whose nature and purpose is not clear at all even after clicking on it and reading the description. I am still personally wondering whether this is aspirationally a place that people would announce Satoshi Squares if they were ever to happen again.

Back to the left nav, we have "Support" followed by "User options" and "Settings".  The latter two are confusing because at first glance they seem to be the same thing. Most people see "options", "preferences" and "settings" more or less as synonyms and thus expect them to live in one place. It's confusing for this reason to see them separated out as two distinct top level navigation items here. I'm still left wondering what each one means even though I've clicked on them both a dozen times.


With the above issues having been laid out, I'd like to suggest the following redesign of the left nav to resolve them.

```
- Dashboard

- Trade
- Learn
- Discuss
- Contribute

- News
- Support

- Settings
```

"Trade" replaces the more verbose "Trade protocols" noun with a verb that tells the user what they're doing to _do_ if they click this button. The content when clicking on "Trade" would be the same as it was when clicking on "Trade protocols". i.e. it would introduce the user to Bisq 2's concept of trade protocols, and show them the protocols currently available and those coming on the roadmap. One change to that screen, though, would be allowing the user to "favorite" their choice of (implemented) trade protocols, such that those favorites show up in the left nav as sub-items of the "Trade" item, like this:

```
- Trade
    - Bisq Easy
    - Mainchain Multisig
    - Liquid Multisig
    - Lightning Multisig
    - ...
```

Bisq Easy would favorited by default, such that the left nav would look like this when running a freshly installed Bisq 2:

```
- Dashboard

- Trade
    - Bisq Easy
- Learn
- Discuss
- Contribute

- News
- Support

- Settings
```

"Dashboard" stays the same and take the user to the same content for now. (In the future, I think the dashboard needs to actually become the users customized dashboard with market data, offer books, price feeds, etc that they're interested in, but that's an issue for another day.)

"Learn" stays the same and point to the same content.

"Discuss" replaces the "Discussions"  noun with a verb and points to the same content.

"Contribute" is new, see discussion to that effect in https://github.com/bisq-network/bisq2/issues/1848#issuecomment-2019049121

"News" replaces "Events" with a more general term that actually / more naturally encompasses "Conferences", "Meetups", and "Podcasts". (and I suggest just getting rid of the "Trade" channel). Note that "News" is a noun and so breaks with the verbs above it, but I can't think of a good way to make this a verb that isn't contrived or awkward (e.g. "Stay Informed"). News is simple and clean and everybody knows what to expect when clicking it. Note also that this is where I think we should add a "What's New in Bisq 2" / release notes section.

"Support" stays the same, ain't broke, don't fix.

"Settings" consolidates "User options" and "Settings" into one. What the user then sees when clicking on Settings will then necessarily become more complex, but I think it's the right tradeoff to push that complexity down a layer instead of confusing them every time they look at the left nav. If we have to make them think, let's at least defer doing so until they've indicated they're actually interested in settings (whatever they think that word means) by clicking on that button.


...

On having written the above and then mulling it over before hitting send, perhaps the following revised left nav layout would be even better:

```
- Dashboard

- Trade
    - Bisq Easy
- Learn
- Discuss
- Support

- Connect
- Contribute

- Settings
```

The two changes here are hoisting "Support" up and renaming "News" to "Connect".

Now every top level item except "Dashboard" and "Settings" are verbs.

The first group of items lays out core actions you can take _with_ Bisq 2 itself. You can Trade, Learn, Discuss, and (get/receive) Support all right in the app.

The second group lays out ancillary actions you can take _around_ Bisq 2 and its ecosystem. You can Connect through conferences, events, podcasts and articles and matrix chat (user channels). You can Contribute by getting involved with the Bisq DAO and joining matrix chat (contributor channels).

Note: I'd suggest using a newspaper icon next to "Connect" to connote news-like notion of "connecting with timely information"


... 

Coming back full circle, then, to the original topic of this thread, which was the Bisq Reputation Ribbon and its rightful placement in the UI, I don't think it should live as a top-level item in the left nav. I think where it "belongs" is in the "Learn" section. How we prominently direct users' attention to that Learn section is an important matter, and might be accomplished with a banner or status bar message or section on the dashboard or "did you know" modal on app startup or any number of other mechanisms, but I think the left nav should be tightly controlled such that it remains minimal, intuitive and utilitarian to all users throughout their journey from newb to expert. Each of the items listed in the nav mockups above could be clicked by any user at any point in that journey. Some of them might be clicked every day, some seldom or never, but all items are at least _potentially relevant_ to all users at all times. A top-level "Reputation" item doesn't qualify as such, because, when there are other trade protocols implemented, Bisq Reputation may have nothing to do with them. It's just a Bisq Easy thing, at least for now, and if I'm a future user who doesn't use or care about Bisq Easy, I'm going to be annoyed by this Reputation nav item. It's going to feel, however subtly, like spam to me, especially given that the left nav is omnipresent in Bisq 2. Even if it's collapsed, I'm still going to see that ribbon icon, and it's not going to be relevant to me and I'm going to wish, even if just subconsciously, that I could nuke it. The better place for information on the concept of Bisq Reputation to live is in the "Learn" section, and the better place for Reputation data and controls to live is within the Bisq Easy and/or Bisq Easy Settings UI, since that's what the Reputation we're talking about is specific to. So in `Trade > Bisq Easy > Reputation` and/or `Setings > Trade Protocols > Bisq Easy > Reputation` as appropriate.

**Comment by HenrikJannsen** [comment]
@cbeams Good points!

I think reputation should be though beyond its current usage for Bisq Easy. I expect that we will find useful reuse in the Multisig protocol or others (which are not atomic swaps as those do not require trust to the peer).
We have in Bisq 1 the user icons and number of trades which are some sort of limited reputation, as well as account age and account age witness which are reputation systems by itself.

I think reputation might be best to separate into my reputation and how to build it as part of user options.
The other part to see the peers reputation and one own's reputation in that context could be seen similar as network and become a part of the dashboard (state of the user network and node network).
A widget with graphically pleasing content (some dynamic graphs) and link to a larger screen with details when clicked might be an alternative to the main menu item. This places can be be linked from various contexts to get better chance that the user sees it. We also can use the new Alert display (similar to the notification pane) to promote it.  

Network might get removed from Settings and added as as well as a widget in Dashboard with minimal network specific metrics graphically pleasing presented and with click on it to open to a larger screen with details. Note, that it is also linked from the left bottom network icons (tor). 

We could add a link from click on the user icon at the top right to go to the user options.

I am not that sure if we should add the Connect/Contribute items.
So far, the idea of Event seems to not have worked out anyway. So maybe we should just drop that. It might become also problematic to manage once shitcoiners come to promote their next airdrop...
And we might risk to overload the app with things which are better place at the webpage, Matrix or GH. At least for now, I think we better focus on the core elements.

The whole Learn, Event, Discuss have been an experiment. Its probably too early to tell but at least the Events seems to be not much used or if so, not in the intended manner.
Not sure about Learn as currently we have likely mostly Bisq1 users who are not the target audience for that.

I think adding a submenu for trade protocols in Settings should be delegated when we actually need it. Many settings might have global effect and those which are specific might live in sub-tab-view inside the Preferences.

Regarding sub-menu in the left nav: We had that earlier (all protocols have been sub menu items) but it resulted in a hard problem how to deal with it on min. screen size as we did not want to show a scroll bar at the left nav. 
We can delegate that problem to later once more protocols would get added and fill up so much space that this becomes a problem again. Just wanted to mention it. Another smaller problem was that when horizontally collapsed the sub menu items have not been that clear distinguishable from the main items.


I would suggest following:

```
- Dashboard (add reputation and network widget)

- Trade
    - Bisq Easy
- Learn
- Discuss
- Support

- User options
- Settings
```

**Comment by HenrikJannsen** [comment]
Actually after a second though I am not that sure anymore about adding reputation and network to the dashboard.
Our target for Bisq Easy are newbies and we do not want to overload them with complex information which is not needed to them. Reputation is more important to sellers.

One option to serve both newbies and experts better could be to use the 2 boxes below as switches (Best for newcomeser, Best for experts) and when the user clicked on those the screen changes to 2 variants optimized for those user groups.
The selection could be moved to the top as tabs so the user could switch between them if not sure...
Just an idea... would need more time to work out...
