### ISSUE TITLE
Add "Developers" chat room

### ISSUE THREAD

**Issue by HenrikJannsen** [bisq-network/bisq2#1848]
Maybe we should add a chat for development specific issues. The Off-Topic room has become a bit for that already. It would help also to attract new devs.

**Comment by HenrikJannsen** [comment]
@cbeams Do you have any recommendation to that?

**Comment by axpoems** [comment]
I suggest we add a new section in the left main menu with "Contribute to Bisq" or "Become a Bisq dev" dedicated to this.
Then we can have a tab with an info section and another one for a chat.
For the info section, a good content would be the Bisq2 readme, which was updated recently.

**Comment by cbeams** [comment]
Regarding actually adding a "Dev" chat channel to Bisq 2, I think it's better to direct would-be devs and serious contributors to Matrix. Perhaps Bisq 2's p2p group chat will evolve to be fully featured enough to be the home of dev/contributor chat for the project, but it's not there yet, and I doubt that it's a goal worth going after in the end.

So rather than bifurcate the dev / contributor chat more than it already is (across various Bisq Matrix chat rooms), I'd direct folks who want to contribute beyond basic feedback to join us on Matrix.

This could be done in the left nav as has been discussed, with a "Contribute" item, but I don't feel strongly that's the only place to do it. If there were such a left nav item, though, I'd imagine that clicking on it would show the user some information about the Bisq DAO, BSQ and key team resources like Matrix.

**Comment by HenrikJannsen** [comment]
I agree that we should not add that at the current state at least. Less is more....

If no opposition I would close that issue.
