### ISSUE TITLE
Let buyer makers set a fixed or maximum allowable markup

### ISSUE THREAD

**Issue by suddenwhipvapor** [bisq-network/bisq2#1890]
Just like seller makers can set their price deviation, I think buyer makers should be allowed to set a fixed price deviation they are willing to pay.
Before, I thought a hidden field could be added, to fill in the "max markup I can accept", so that sellers trying to take the offers would immediately receive a "price too expensive for this buyer" notification, but then I though a hidden/public field like that just complicates things, and it's easier and clearer to have an explicit % deviation offerbook like in bisq1.

The advantage, briefly speaking, is saving users from wasting time if a buyer receives a taker who asks too much and has to reject the trade.
This feature would make #1889 almost moot, but showing price and deviation in the trade info panel is probably still a good idea no matter what.

**Comment by HenrikJannsen** [comment]
The reason why we did not do that was because it would very likely lead to the situation that the BUY offers use prices around market rate and sellers will not be motivated to take those offers due the costs for reputation, minerfee, effort for being the friendly guide and effort for usually small amounts. Explaining all those things to newbies would be counter to the intent of Bisq Easy. A newbie might not even know what miner fees are or how high they usually are.

But we are aware that we have a weak point open since the trade protocol changes where both traders could send in parallel their payment data. Thus if a seller as taker sends quickly the data the buyer as maker cannot reject the offer without breach of contract if they dont like to accept the price the seller has set. 
I fear we need an extra accept stage in the protocol where the buyer explicitly accept the sellers price. Maybe that happens even outside the protocol as precondition to start the trade. But that will be a bit more complex and larger change and difficult to handle backward compatibility.

**Comment by HenrikJannsen** [comment]
Covered by https://github.com/bisq-network/bisq2/issues/1949
