### ISSUE TITLE
Error message when taking an offer

### ISSUE THREAD

**Issue by leo816** [bisq-network/bisq2#1973]
I'm trying to take an offer to sell Bitcoin (have reputation and everything ready) but get this error:
<img width="887" alt="Screenshot 2024-04-02 at 12 33 15" src="https://github.com/bisq-network/bisq2/assets/54798241/5eb9df19-82fb-4a12-9059-1ad1b07dd7bb">

If I try to take it again and ignore the error message and introduce a price, I still get an error about having the wrong price range (when its we within)
<img width="907" alt="Screenshot 2024-04-02 at 12 34 23" src="https://github.com/bisq-network/bisq2/assets/54798241/edb71bf3-4eb0-4ab9-8ad1-650293097a1b">

**Comment by mpenagar** [comment]
I get a similar problem, but just with some offers (they always fail, but some others do work). I can know the error will occur in the first step, since the "negotiation price" textfield is empty:
<img width="374" alt="bisq2-1" src="https://github.com/bisq-network/bisq2/assets/1698682/bcb8114a-9c2f-4355-b103-43e05e689ab0">
If I try to set any percentage (using many different formats), it fails:
<img width="621" alt="bisq2-2" src="https://github.com/bisq-network/bisq2/assets/1698682/97dace5a-9f1d-455a-a9dd-a071b80c8b1b">
I tried with different offers from the same user and it allways fails. Could be relatet to the user?

**Comment by HenrikJannsen** [comment]
This is fixed for next release.
It is caused by the language difference of the maker and yourself. Top mitigate with current version you can either change your language to the estimated of the maker or to take another offer in the same language.
