### ISSUE TITLE
An error occurred at initializing Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..

### ISSUE THREAD

**Issue by ChuckBronson78** [bisq-network/bisq2#2107]
An error occurred at initializing Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..

Attached is Bisq report:...
[Uploading bisq.log…]()

**Comment by HenrikJannsen** [comment]
The log upload did not succeed. Which version are you using? Which OS?

**Comment by jdmconnected** [comment]
I get the same error. Windows 11, Bisq 2 2.0.3
[bisq2_log.txt](https://github.com/bisq-network/bisq2/files/15143178/bisq2_log.txt)
![image](https://github.com/bisq-network/bisq2/assets/30991606/921bd502-6ed4-4068-bf5c-b3f8f0d984ba)

**Comment by Air4Andy** [comment]
Same issue here

**Comment by HenrikJannsen** [comment]
Should be fixed with v2.0.4. It is available as pre-release at https://github.com/bisq-network/bisq2/releases/tag/v2.0.4 (if you enable notifications for pre-release in the preferences you get the update notification).
Can you try it out?
If you still get the issues, please let me know so that I re-open.
