### ISSUE TITLE
Error when launching Bisq2

### ISSUE THREAD

**Issue by tnperron** [bisq-network/bisq2#2130]
Error message when trying to start Bisq2.  Bisq.log attached.
[Uploading bisq.log…]()

`An error occurred at initializing Bisq: bisq.tor.controller.exceptions.HsDescUploadFailedException: HS_DESC upload timeout triggered..`

**Comment by tnperron** [comment]
Unable to confirm, but Bisq1 may have also been running at the time that error was generated.  After a fresh boot and confirming nothing else running in the background that might interact with tor, Bisq2 is launching successfully.

Tried launching Bisq2 with Bisq1 running already and it worked this time.  Also tried having the tor browser running, was still able to launch successfully.

**Comment by HenrikJannsen** [comment]
Should be fixed with next release.

**Comment by HenrikJannsen** [comment]
Should be fixed with v2.0.4. It is available as pre-release at https://github.com/bisq-network/bisq2/releases/tag/v2.0.4 (if you enable notifications for pre-release in the preferences you get the update notification).
Can you try it out?
If you still get the issues, please let me know so that I re-open.
