### ISSUE TITLE
Ocorreu um erro ao inicializar o Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..

### ISSUE THREAD

**Issue by rriill** [bisq-network/bisq2#2137]
Ocorreu um erro ao inicializar o Bisq: bisq
[bisq.log](https://github.com/bisq-network/bisq2/files/15181717/bisq.log)
.tor.controller.ControlCommandFailedException: Couldn't connect to control port..

**Comment by HenrikJannsen** [comment]
Should be fixed with next release.

**Comment by HenrikJannsen** [comment]
Should be fixed with v2.0.4. It is available as pre-release at https://github.com/bisq-network/bisq2/releases/tag/v2.0.4 (if you enable notifications for pre-release in the preferences you get the update notification).
Can you try it out?
If you still get the issues, please let me know so that I re-open.
