### ISSUE TITLE
An error occurred at initializing Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..

### ISSUE THREAD

**Issue by astonappleby** [bisq-network/bisq2#2143]
An error occurred at initializing Bisq: bisq.tor.controller.ControlCommandFailedException: Couldn't connect to control port..
[bisq.log](https://github.com/bisq-network/bisq2/files/15210434/bisq.log)

**Comment by wesleyguitars** [comment]
Me too. Can't use it aymore.

**Comment by HenrikJannsen** [comment]
Can you try to delete the tor folder in the data directory?

**Comment by HenrikJannsen** [comment]
Should be fixed with v2.0.4. It is available as pre-release at https://github.com/bisq-network/bisq2/releases/tag/v2.0.4 (if you enable notifications for pre-release in the preferences you get the update notification).
Can you try it out?
If you still get the issues, please let me know so that I re-open.
