### ISSUE TITLE
Bisq connection error:

### ISSUE THREAD

**Issue by 910314Jost** [bisq-network/bisq2#2191]
When trying several times to open Bisq, the connection fails. So I followed the platform's recommendation to report this error here on Github I will attach the file. Whoever has the courage and patience to analyze the case, I thank you for your good will! 🙂
[bisq arquive.txt](https://github.com/bisq-network/bisq2/files/15327676/bisq.arquive.txt)

**Comment by HenrikJannsen** [comment]
Should be fixed at upcoming release.

**Comment by HenrikJannsen** [comment]
Should be fixed with v2.0.4. It is available as pre-release at https://github.com/bisq-network/bisq2/releases/tag/v2.0.4 (if you enable notifications for pre-release in the preferences you get the update notification).
Can you try it out?
If you still get the issues, please let me know so that I re-open.
