### ISSUE TITLE
 error occurred at initializing

### ISSUE THREAD

**Issue by 91anon93** [bisq-network/bisq2#2193]
An error occurred at initializing Bisq: bisq.tor.controller.exceptions.HsDescUploadFailedException: HS_DESC upload timeout triggered..

System Pop_os

**Comment by HenrikJannsen** [comment]
Should be fixed with v2.0.4. It is available as pre-release at https://github.com/bisq-network/bisq2/releases/tag/v2.0.4 (if you enable notifications for pre-release in the preferences you get the update notification).
Can you try it out?
If you still get the issues, please let me know so that I re-open.

**Comment by 91anon93** [comment]
it works, thanks.
