### ISSUE TITLE
java.util.concurrent.TimeoutException at attempted shutdown

### ISSUE THREAD

**Issue by stevednm** [bisq-network/bisq2#2194]
Bisq2 in Linux (Linux Mint 21.3), shutdown issued this error:
java.util.concurrent.TimeoutException

logs attached
[bisq.log](https://github.com/bisq-network/bisq2/files/15342224/bisq.log)

**Comment by HenrikJannsen** [comment]
Should be fixed with v2.0.4. It is available as pre-release at https://github.com/bisq-network/bisq2/releases/tag/v2.0.4 (if you enable notifications for pre-release in the preferences you get the update notification).
Can you try it out?
If you still get the issues, please let me know so that I re-open.
