### ISSUE TITLE
Executable signature verification fails using PGP key provided on website 

### ISSUE THREAD

**Issue by AirHache** [bisq-network/bisq2#3029]
Hi, 

I attempted to verify the signatures of Windows executables of Bisq2, using this [public key](https://github.com/bisq-network/bisq2/releases/download/v2.1.2/E222AA02.asc, but it fails).

For Bisq1, it worked perfectly.

**Comment by jivanpal** [comment]
@HenrikJannsen The wiki says Alejandro's key has expired, but this is not the case, or it has since been renewed (current expiry is 3 Oct 2026). Should the key have been revoked?

Providing a link to your (Henrik's) key on the Bisq website and/or having Alejandro's key countersign yours would alleviate any concerns I have.

Which key will be used going forward?

**Comment by HenrikJannsen** [comment]
> @HenrikJannsen The wiki says Alejandro's key has expired, but this is not the case, or it has since been renewed (current expiry is 3 Oct 2026). Should the key have been revoked?
> 
> Providing a link to your (Henrik's) key on the Bisq website and/or having Alejandro's key countersign yours would alleviate any concerns I have.
> 
> Which key will be used going forward?

It has been renewed. It was just at the release date. 

Alejandro's key will be used again in follow up releases. This was only to avoid that in in-app download verification fails. My key was always included in the supported keys list.
