### ISSUE TITLE
ElectrumDownloader: Investigate why Emzy's key fails signature validation

### ISSUE THREAD

**Issue by alvasw** [bisq-network/bisq2#556]
We use keys of ThomasV, Emzy, and SomberNight to verify the integrity of the Electrum binaries. When I implemented the ElectrumPlugin I didn't have the time to investigate why Emzy's key fails.
https://github.com/bisq-network/bisq2/blob/256256272e4924b8c9b4aadae4cd1d22323e66e9/build-logic/electrum-binaries/src/main/kotlin/bisq/gradle/electrum/tasks/VerifyElectrumBinariesTask.kt#L63

**Comment by Emzy** [comment]
I assume it has something with the expiration date of the key to do.
The signing sub key expired about 3 weeks ago. So I extended the expiration date of that key.
New public key is on the pgp keyservers and here:
https://github.com/Emzy/electrum/blob/master/pubkeys/Emzy.asc

Or the software checks the fingerprint of the signing key instead of the master key.
Signing sub key fingerprint is: 637D B1E2 3370 F84A FF88  CCE0 3152 347D 07DA 627C
